# Generated by Django 6.0.4 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('previous_company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('current_salary', models.IntegerField()),
                ('expected_salary', models.IntegerField()),
            ],
        ),
    ]
